### ISSUE TITLE
Share most recently created climb with all users

### ISSUE THREAD

**Issue by nicholasbergesen** [nicholasbergesen/boulderlog#11]
Display the most recently created climb across all users on the home page, allow users to claim this and add it to their account. This saves them needing to capture the same details.

Features
- [x] https://github.com/nicholasbergesen/boulderlog/issues/26
- [x] https://github.com/nicholasbergesen/boulderlog/issues/29
- [x] https://github.com/nicholasbergesen/boulderlog/issues/30

**Comment by nicholasbergesen** [comment]
woop woop, finally done
